enum Alteration {
  DEFAULT = "Default",
  ATTRACTION = "Attraction",
  CONFUSION = "Confusion",
  MALEDICTION = "Malédiction",
  PEUR = "Peur",
  IDENTIFIE = "Identifié",
  VAMPIGRAINE = "Vampigraine",
  PIEGE = "Piège",
  SOMNOLENT = "Somnolent",
  CAUCHEMAR = "Cauchemar",
  STOCKAGE = "Stockage",
  PRELEVEMENT_DU_DESTIN = "Prélèvement du Destin",
  ENCORE = "Encore",
  PROVOC = "Provoc",
  TOURMENTE = "Tourmente",
  EMBARGO = "Embargo",
  ABRI = "Abri",
  CLONE = "Clone",
  ENTRAVE = "Entrave",
  POSSESSIF = "Possessif",
  VEROUILLAGE = "Verouillage",
  REQUIEM = "Requiem",
  ANTI_SOIN = "Anti-soin",
  RACINES = "Racines",
  ANNEAU_HYDRO = "Anneau Hydro",
  SAISIE = "Saisie",
  VOL_MAGNETIK = "Vol Magnetik",
  LEVIKINESIE = "Levikinésie",
  A_TERRE = "A terre",
  CHANGEMENT_DE_TYPE = "Changement de type",
}

export default Alteration;
// https://www.metamorph6iv.net/t31427-notion-strategique-les-statuts-et-alteration-d-etat
